FROM node:14.15.3

ARG JWT_SECRET=${JWT_SECRET}
ARG EMAIL_SERVER_ENDPOINT=${EMAIL_SERVER_ENDPOINT}
ARG EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}
ARG MONGO_DB=${MONGO_DB}
ARG STRIPE_PUBLISHABLE_KEY_TEST=${MONGO_DB}

RUN mkdir -p /usr/src/epitrade-app
WORKDIR /usr/src/epitrade-app
COPY . /usr/src/epitrade-app/

RUN npm install
RUN npm run build

EXPOSE 80

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=80

CMD [ "npm", "run", "start" ]
